services:
    wordpress:
        build: ./requirements/wordpress/
        image: wordpress
        container_name: wordpress
        restart: unless-stopped
        env_file: .env
        depends_on:
            - mariadb
        volumes:
            - wordpress_data:/var/www/html
        networks:
            - inception
        secrets:
            - wp_editor_password
            - db_password
            - wp_admin_password

    mariadb:
        build: ./requirements/mariadb/
        container_name: mariadb
        image: mariadb
        restart: unless-stopped
        env_file: .env
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - inception
        secrets:
            - db_password
            - db_root_password

volumes:
    wordpress_data:
        name: wordpress_data
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/${USER}/data/wordpress/
    mariadb_data:
        name: mariadb_data
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/${USER}/data/mariadb/

networks:
    inception:
        name: inception
        driver: bridge

secrets:
    db_password:
        file: ../secrets/db_password.txt
    db_root_password:
        file: ../secrets/db_root_password.txt
    wp_admin_password:
        file: ../secrets/wp_admin_password.txt
    wp_editor_password:
        file: ../secrets/wp_editor_password.txt
